= uProtocol Transport Interface & Data Model
:toc:
:sectnums:
:source-highlighter: prettify

== Overview
The following section implements https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/up-l1/README.adoc[uP-L1 Transport Layer Specifications]. The purpose of the transport layer is to wrap communication middlewares into a common interface that allows us to send and receive any kind of uProtocol messages (publish, request, response, notification) over any kind of transport (HTTP, MQTT, WebSockets, etc).

the datamodel is declared in the uProtocol specifications project in https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/up-l1/README.adoc[up-core-api] folder and this project declares the language specific transport interface (UListener & UTransport) and the builders, serializers, and validators, for the up-core-api data model. .

Below are the list of the classes and interfaces that are part of the uProtocol Transport Interface & Data Model:

.Transport Interfaces
[table-transport-interfaces, cols="1,3"]
|===
| Class/Interface | Description

| xref:UTransport.kt[*`UTransport`*]
| Interface that defines the methods that a transport middleware must implement in order to be used by the uProtocol library.

| xref:UListener.kt[*`UListener`*]
| Callback/listener interface to be able to receive messages from a transport.

| xref:UMessageKtExt.kt[*`UMessageKtExt`*]
| Kotlin Dsl to build request, response, publish and notification UMessage, and set functions to set attributes.

| xref:validator/UAttributesValidator.kt[*`UAttributesValidator`*]
| uProtocol Attributes validator that ensures that the publish, notification, request, and response messages are built with the correct information.

|===

== Examples

In the following section we will provide an example for how a transport implementations are expected to implement the uTransport library

[source,kotlin]
----
include::../../../../../../test/kotlin/org/eclipse/uprotocol/communication/TestUTransport.kt[]
----