name: Continuous Integration

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

    - name: Set up Apache Maven Central
      uses: actions/setup-java@e9fbacdec3bb3b6036605a3e6f7995d66773a8c6 # v3.14.2
      with: # configure settings.xml
        distribution: 'temurin'
        java-version: '17'
        server-id: ossrh
        server-username: OSSRH_USER
        server-password: OSSRH_PASSWORD

    - name: Build and Publish to OSSRH snapshot repo
      run: mvn clean deploy
      env:
        OSSRH_USER: ${{ secrets.ORG_OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.ORG_OSSRH_PASSWORD }}
